# Generated by Django 4.2 on 2023-04-15 06:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_rename_categorys_categories_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='categorys',
            new_name='category',
        ),
    ]
