# Generated by Django 4.2 on 2023-04-15 06:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_rename_categorys_product_category'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Categories',
            new_name='Categorys',
        ),
    ]
