# Generated by Django 4.2 on 2023-04-15 06:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_rename_categories_categorys'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Categorys',
            new_name='Category',
        ),
    ]
